### ISSUE TITLE
Flask response with NaN 

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic#116]
It seems that having `numpy.nan` in the returned json data produces an error response with status `200/OK` while still delivering the data.

Suggesting replacing all `nan` and `inf` with `None` or similar.

**Comment by local-minimum** [comment]
The real problem might be that no abort codes were ever used as they should have been. I've started rewriting api to return correct status-codes.

**Comment by local-minimum** [comment]
@skymandr pull request #135 converts some more. It would be good to go through the endpoints and fix this for all of them, but there's a risk that the web-app will malfunciton in many places. @Endimion75 do you think the app will handle other status-codes or will there be an extensive need of testing all the QC-features?

**Comment by Endimion75** [comment]
@local-minimum: I am not sure what are you referring to, but the UI is hardwire to expect certain values from the API if you change them, the UI will break naturally.

**Comment by skymandr** [comment]
Close?
