### ISSUE TITLE
API: detect colony error

### ISSUE THREAD

**Issue by Endimion75** [Scan-o-Matic/scanomatic#119]
When using the path:

`/api/data/calibration/<ccc_identifier>/image/<image_identifier>/plate/<plate>/detect/colony/<x>/<y>`

And the x,y parameters do not match the current plate grid I get a response from the API as an error.  By this I mean an error response, not a success response with an API custom error.

The data I receive has:

readyState:0
Status:0
StatusText:"error"

It would help a lot to know I generated an out of index exception or something else, so I can report the right problem.  

I imagine the problem is that the x,y coordinates does not match the plate positions, but it is very hard to know.

The plate is a 96 well plate and it correctly processed coordinates:

1,0
2,0
3,0
4,0
5,0
6,0
7,0

0,1 causes this error

Even if I inverted rows and columns, the plate should have a 1,0 valid colony, right?

**Comment by local-minimum** [comment]
Does this error happen after gridding failed? If gridding failed, this step shouldn't really work and there shouldn't be any correct colony coordinate at all really so even [0,0] should fail.

**Comment by skymandr** [comment]
Might I request that this is tried again with the latest version to rule out that it was a symptom of the same problem as in issue 118?
