### ISSUE TITLE
setup.py fails to pull in setproctitle as a dependency

### ISSUE THREAD

**Issue by pmagwene** [Scan-o-Matic/scanomatic#125]
setup.py fails to pull in setproctitle as a dependency, leading to ImportError during setup

**Comment by local-minimum** [comment]
I was about to say that this is implemented in just lacks testing, but it could be that `setproctitle` doesn't work on windows with anaconda but it does work on `Bash on Ubuntu on Windows`-thing for windows 10. As you've probably have noticed, it takes a bit of work to get everything up and running, and we are therefore looking into creating a cloud service to simplify the process for the end-user.

**Comment by local-minimum** [comment]
We've now migrated to using docker to build images, we haven't released the first one yet though, so with that one, this should not be an issue anymore.
