### ISSUE TITLE
Feature Request: Instruction to use V800 or other scanners

### ISSUE THREAD

**Issue by pmagwene** [Scan-o-Matic/scanomatic#126]
A brief README detailing changes required to use Epson V800 (or other scanners) would be greatly appreciated.

**Comment by local-minimum** [comment]
There's info on the wiki for setting up supported scanners:

https://github.com/local-minimum/scanomatic/wiki/Installing-scanners

And shortly about non-supported scanners here:

https://github.com/local-minimum/scanomatic/wiki/Installation-Questions-&-Answers#sane-and-scanners
