### ISSUE TITLE
CCC manual colony metadata curation subtool

### ISSUE THREAD

**Issue by Endimion75** [Scan-o-Matic/scanomatic#136]
It was decided that the metadata curation tool would only have to mark the "blob" pixels, and the rest will be consider "background" except for the ones that have already been marked by the system as "neither".

I have encountered several case where the system didn't manage to mark the "neither" pixel correctly and instead marked them as background. like so:

![sc4](https://user-images.githubusercontent.com/14052981/27741214-a1f2c4b0-5db4-11e7-9348-defd328c07bd.png)

With the current logic the curation will not properly address the true "neither" areas like so:

![sc5](https://user-images.githubusercontent.com/14052981/27741279-deffe04a-5db4-11e7-9871-9688b3b4b520.png)

**Question: will this cause serious problem?**  
**Is the capacity to mark neither pixels a must after seeing this?**

**Comment by local-minimum** [comment]
@Endimion75 minor detail: You have `Either` in the UI and it should have been `Neither` but as that word isn't that understandable so I suggest we use the term `Discarded`.

In the current case we do have a problem if we want to have the "colony" included. In this case there's obviously no cells in the colony image and perhaps the easy way out is to say that the user should just discard this position and move on to the next one without including it in the analysis. All other alternatives requires live painting of `Discarded` areas in the image.

**Comment by local-minimum** [comment]
@Endimion75 if you've changed wording in app to `Discarded` or `Excluded` or similar and agree that we go with the idea that the user needs to omit these from the analysis, then feel free to close the issue.

**Comment by Endimion75** [comment]
I agree with the wording and in for now, lets discard the colony until we have a working prototype and then I can try to add more tooling to the manual metadata annotation subsystem.
