### ISSUE TITLE
Update API endpoints to use http abort codes instead of success=False/True

### ISSUE THREAD

**Issue by skymandr** [Scan-o-Matic/scanomatic#140]
Some endpoints have already been updated to use `jsonify` for successful calls and `json_abort` with appropriate error code for failed, but most remain. There is also the issue, that all endpoints still use both `success=False/True` and return a status code.

DoD: API calls no longer use the `success=` paradigm. Failed calls return appropriate status codes.

**Comment by skymandr** [comment]
There is also the issue, at least in the `calibration_api.py`, that some failures assume authentication failure, but are not sure about it. These should be made sure, so that the status code is meaningful.

**Comment by local-minimum** [comment]
I don't think this has to be an open issue anymore. We will work towards this but we will not do a focused replacement.
