### ISSUE TITLE
CCC api may have concurrecy issues

### ISSUE THREAD

**Issue by skymandr** [Scan-o-Matic/scanomatic#147]
From #146:

> Finally, and that's a big one, I think that there are concurrency issues here. It's not only the delete function, all the endpoint that manipulate the CCCs are likely to be affected. But it includes the delete one.
> A relatively likely scenario is that the user double clicks on the delete button (because too much :coffee:? ;-)) which triggers two runs of delete_non_deployed_calibration.
> One problem is that, if the stars are right, the parallel executions can be interleaved in a way that results in the CCC in memory being different than the one on disk. The other issue is that running save_ccc_to_disk in parallel will likely ends up in a garbled, unreadable file.

DoD: Make sure the endpoints are safe from over caffeinated users.

**Comment by skymandr** [comment]
Would appreciate comments by @local-minimum and @gdetrez if you have any.

**Comment by skymandr** [comment]
Proposed solution after IRL discussion: start using databases instead of filesystem for configuration/settings etc. Postgresql is a promising candidate. Currently, however, the service is running in single thread mode, so this is not an issue until it is scaled up for truly networked use.

**Comment by gdetrez** [comment]
This should now be *mostly* solved. I suggest we open new issues in case we find problem with it.
