### ISSUE TITLE
Volume as endpoint for data

### ISSUE THREAD

**Issue by dindinoh** [Scan-o-Matic/scanomatic#149]
Make both scan-o-matics use static volume as mount in docker.
Make it so docker mounts a volume for images.
Remove UI setting for choosing storage point.

**Comment by dindinoh** [comment]
changed description of issue according to @skymandr comment https://github.com/Scan-o-Matic/scanomatic/pull/155#pullrequestreview-60848459

**Comment by skymandr** [comment]
Close?
