### ISSUE TITLE
It's difficult to find a scanner in the new job form

### ISSUE THREAD

**Issue by gdetrez** [Scan-o-Matic/scanomatic#337]
At some point, I had 30+ test scanners in Scan-o-Matic and needed to create a scanning job with a particular scanner. I found it rather difficult to find it in the drop-down.

I have two suggestions to make the list more readable:
- sort the scanners by name
- remove "The" from the name generation. It just adds noise.

**Comment by skymandr** [comment]
I second both suggestions.
