### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic#68]
A comprehensive uninstall would be good.

Yes/no removal of:

* `scan-o-matic*` executables for binary folder
* `Scan-o-Matic.*.egg` and `scan-o-matic` lib python file and folders
* Removal of non-config local data
* Removal of all local data.

**Comment by local-minimum** [comment]
`python setup.py uninstall` will trigger this but not yet with local configs nor complete removal of local data.

**Comment by skymandr** [comment]
Though this might still be nice to have, in case someone wants to run it outside docker, the task no longer reflects the majority user, right? This task should perhaps be updated to include the case of removing dockerized scan-o-matic (mainly cleaning up volumes?). Either that, or create a new issue for this.

**Comment by local-minimum** [comment]
I think we just close this one and if there really is a reason for cleaning up images we make that issue when we have it.
