### ISSUE TITLE
Configurational mismatch: QC vs actual scanned image

### ISSUE THREAD

**Issue by payamghiaci** [Scan-o-Matic/scanomatic#89]
In QC we look at the plate from above whereas the actual scanned images are showing the plate from below. It takes some imagination to superpose the two images. Why not following the same configuration of scanned image in the QC ...

**Comment by local-minimum** [comment]
A potential alternative is if you request plate images from the QC and get to see them as if from above too?

**Comment by payamghiaci** [comment]
Yes. Could be.

**Comment by local-minimum** [comment]
I will close this task in favour of #172 that generalizes the issue.
