### ISSUE TITLE
Scanning shows >100% 

### ISSUE THREAD

**Issue by StenbergSimon** [Scan-o-Matic/scanomatic#93]
It seems that on some computers, the completion exceeds 100%. It seems like they also take longer to finish so there might be some issue of the time lagging behind for some reasons.

**Comment by local-minimum** [comment]
I would need a `scan.instructions` and `scan.log` file to check cause as a minimum. IF there's a relevant `server.log` it would also help.

**Comment by local-minimum** [comment]
I would also like to know if this issue is exposed on `master` and/or other branches.

**Comment by StenbergSimon** [comment]
Here are the files:
[logs.zip](https://github.com/local-minimum/scanomatic/files/699355/logs.zip)

The version used is dev branch v. 1.4.85

**Comment by local-minimum** [comment]
Investigated the code and there's no reason why the interval would overshoot, it correctly enters next mode in its iteration cycle when passing the time threshold and this is tested twenty times a second. 

I added a bit more logging on the scanning and this is ready for a debug run on the bad machine from experimental branch.

Plausible reasons to check for

- [ ] The scan cycle of previous image doesn't complete on time
- [ ] The computer is running on maximum CPU and or MEMORY
- [ ] The python function `time.time()` is not reporting time correctly on that machine.

**Comment by local-minimum** [comment]
@StenbergSimon please use `v1.4.138` on dummy scanning (only needs to be a handful images of nothing) and send me the log-files.

**Comment by local-minimum** [comment]
I would also urge that this computer not be used for scientific experiments until issue is resolved.

**Comment by local-minimum** [comment]
This does not apply to the new Scan Jobs.
